name: Basic workflow

on:
  push:
    branches: [main]
    paths:
      - "**.js"
      - "package.json"
  pull_request:
    branches: [main]
    paths:
      - "**.js"
      - "package.json"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: action/setup-node@v4
        with: 
          node-version: "20"
          cach: "npm"

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test
